# Chapter 5
# Following the examples worked through in the chapter with modifications
# to players/teams used. Written by Mike Nowicki.

require(curl)
require(data.table)
require(dplyr)
require(chron)
require(plyr)
require(ggplot2)
require(retrosheet)
require(pitchRx)
require(Lahman)

team_ids <- getTeamIDs(2015)
# Ensure the csv file is in R's working directory before running this
pbpdata2015 <- read.csv("data/all_data.csv", header = FALSE)
# Fields csv has been reduced to the 36 common fields generated by BEVENT
fields <- read.csv("data/fields.csv")
names(pbpdata2015) <- fields[,"Header"]

pbpdata2015$RUNS <- with(pbpdata2015, AWAY_SCORE_CT + HOME_SCORE_CT)
pbpdata2015$HALF_INNING <- with(pbpdata2015, paste(GAME_ID, INN_CT, BATTING_TM))

pbpdata2015$RUNS_SCORED <- with(pbpdata2015, (BAT_DEST_ID > 3) + (RUN1_DEST_ID > 3) + (RUN2_DEST_ID > 3) + (RUN3_DEST_ID > 3))
RUNS_SCORED_INNING <- aggregate(pbpdata2015$RUNS_SCORED, list(HALF_INNING=pbpdata2015$HALF_INNING), sum)
RUNS_SCORED_START <- aggregate(pbpdata2015$RUNS, list(HALF_INNING=pbpdata2015$HALF_INNING), "[",1)

MAX <- data.frame(HALF_INNING = RUNS_SCORED_START$HALF_INNING)
MAX$x <- RUNS_SCORED_INNING$x + RUNS_SCORED_START$x

pbpdata2015 <- merge(pbpdata2015, MAX)
N <- ncol(pbpdata2015)
names(pbpdata2015)[N] <- "MAX_RUNS"

pbpdata2015$RUNS_ROI <- with(pbpdata2015, MAX_RUNS - RUNS)
RUNNER1 <- ifelse (as.character(pbpdata2015[,"BASE1_RUN_ID"]) == "", 0, 1)
RUNNER2 <- ifelse (as.character(pbpdata2015[,"BASE2_RUN_ID"]) == "", 0, 1)
RUNNER3 <- ifelse (as.character(pbpdata2015[,"BASE3_RUN_ID"]) == "", 0, 1)

get.state <- function(runner1, runner2, runner3, outs) {
  runners <- paste(runner1, runner2, runner3, sep="")
  paste(runners, outs)
}
pbpdata2015$STATE <- get.state(RUNNER1, RUNNER2, RUNNER3, pbpdata2015$OUTS_CT)

NRUNNER1 <- with(pbpdata2015, as.numeric(RUN1_DEST_ID == 1 | BAT_DEST_ID == 1))
NRUNNER2 <- with(pbpdata2015, as.numeric(RUN1_DEST_ID == 2 | RUN2_DEST_ID == 2 | BAT_DEST_ID == 2))
NRUNNER3 <- with(pbpdata2015, as.numeric(RUN1_DEST_ID == 3 | RUN2_DEST_ID == 3 | RUN3_DEST_ID == 3 | BAT_DEST_ID == 3))
NOUTS <- with(pbpdata2015, OUTS_CT + EVENT_OUTS_CT)
pbpdata2015$NEW_STATE <- get.state(NRUNNER1, NRUNNER2, NRUNNER3, NOUTS)

pbpdata2015 <- subset(pbpdata2015, (STATE != NEW_STATE) | RUNS_SCORED > 0)

# Adjust for partial half innings
data.outs <- ddply(pbpdata2015, .(HALF_INNING), summarize, Outs.Inning=sum(EVENT_OUTS_CT))
pbpdata2015 <- merge(pbpdata2015, data.outs)
pbpdata2015C <- subset(pbpdata2015, Outs.Inning == 3)

RUNS <- with(pbpdata2015C, aggregate(RUNS_ROI, list(STATE), mean))

RUNS$Outs <- substr(RUNS$Group, 5, 5)
RUNS <- RUNS[order(RUNS$Outs),]
# Creates the run expectancy matrix
RUNS.out <- matrix(round(RUNS$x, 2), 8, 3)
dimnames(RUNS.out)[[2]] <- c("0 Outs", "1 Out", "2 Outs")
dimnames(RUNS.out)[[1]] <- c("000", "001", "010", "011", "100", "101", "110", "111")

# Compute the value of a batting play
RUNS_POTENTIAL <- matrix(c(RUNS$x, rep(0, 8)), 32, 1)
dimnames(RUNS_POTENTIAL)[[1]] <- c(RUNS$Group.1, "000 3", "001 3", "010 3", "011 3", "100 3", "101 3", "110 3", "111 3")
pbpdata2015$RUNS_STATE <- RUNS_POTENTIAL[pbpdata2015$STATE, ]
pbpdata2015$RUNS_NEW_STATE <- RUNS_POTENTIAL[pbpdata2015$NEW_STATE, ]
pbpdata2015$RUNS_VALUE <- pbpdata2015$RUNS_NEW_STATE - pbpdata2015$RUNS_STATE + pbpdata2015$RUNS_SCORED

roster2015 <- read.csv("data/roster.csv", header=FALSE)
dimnames(roster2015)[[2]] <- c("playerID", "Last_Name",  "First_Name", "BH", "TH", "teamID", "Position")

# Analysis of player, using Donaldson instead of Pujols
josh.id <- subset(roster2015, roster2015$Last_Name == "Donaldson" & roster2015$First_Name == "Josh")
josh.id <- as.character(josh.id$playerID)
josh <- subset(pbpdata2015, pbpdata2015$BAT_ID == josh.id)
josh <- subset(josh, josh$BAT_EVENT_FL == TRUE)
josh$RUNNERS <- substr(josh$STATE, 1, 3)
table(josh$RUNNERS)

with(josh, stripchart(RUNS_VALUE ~ RUNNERS, vertical=TRUE, jitter=0.2, xlab="RUNNERS", method="jitter", pch=1, cex = 0.8))
abline(h=0)

J.runs <- aggregate(josh$RUNS_VALUE, list(josh$RUNNERS), sum)
names(J.runs)[2] <- "RUNS"
J.PA <- aggregate(josh$RUNS_VALUE, list(josh$RUNNERS), length)
names(J.PA)[2] <- "PA"
J <- merge(J.PA, J.runs)
sum(J$RUNS) # Totals 55.81676, not bad for the 2015 MVP

# Compare against all hitters
pbpdata2015b <- subset(pbpdata2015, BAT_EVENT_FL == TRUE)
runs.sums <- aggregate(pbpdata2015b$RUNS_VALUE, list(pbpdata2015b$BAT_ID), sum)
runs.pa <- aggregate(pbpdata2015b$RUNS_VALUE, list(pbpdata2015b$BAT_ID), length)
runs.start <- aggregate(pbpdata2015b$RUNS_STATE, list(pbpdata2015b$BAT_ID), sum)

names(runs.sums) <- c("Batter", "Runs")
names(runs.pa) <- c("Batter", "PA")
names(runs.start) <- c("Batter", "Runs_Start")
runs <- merge(runs.sums, runs.pa)
runs <- merge(runs, runs.start)

runs400 <- subset(runs, PA >= 400)
with(runs400, plot(Runs_Start, Runs))
with(runs400, lines(lowess(Runs_Start, Runs)))
abline(h=0)

# Identify some of the top producers
runs400.top <- subset(runs400, Runs >= 40)
runs400.top <- merge(runs400.top, roster2015, by.x = "Batter", by.y = "playerID")
with(runs400.top, text(Runs_Start, Runs, Last_Name, pos=1))

get.batting.pos <- function(batter) {
  tb <- table(subset(pbpdata2015, BAT_ID == batter)$BAT_LINEUP_ID)
  names(tb)[tb == max(tb)][1]
}
positions <- sapply(as.character(runs400$Batter), get.batting.pos)

with(runs400, plot(Runs_Start, Runs, type="n"))
with(runs400, lines(lowess(Runs_Start, Runs)))
abline(h=0)
with(runs400, text(Runs_Start, Runs, positions))

JD <- subset(runs400, runs400$Batter == josh.id)
points(JD$Runs_Start, JD$Runs, pch=19, cex=3)

# Section 5.8, homerun values vs single values
d.homerun <- subset(pbpdata2015, EVENT_CD == 23)
table(d.homerun$STATE)
round(prop.table(table(d.homerun$STATE)), 3)
library(MASS)
truehist(d.homerun$RUNS_VALUE)

subset(d.homerun, RUNS_VALUE == max(RUNS_VALUE))[1,c("STATE", "NEW_STATE", "RUNS_VALUE")]
mean.hr <- mean(d.homerun$RUNS_VALUE)
abline(v=mean.hr, lwd=3)
text(1.5, 5, "Mean Runs Value", pos=4)

# Similar analysis to get the value of a single:
d.single <- subset(pbpdata2015, EVENT_CD == 20)
truehist(d.single$RUNS_VALUE, xlab = "Runs Value")

mean.single <- mean(d.single$RUNS_VALUE)
abline(v=mean.single, lwd=3)
text(0.75, 5, "Mean Runs Value", pos=4)

# The most valuable single was McCutchen July 29 lining to right, scoring two runs, then scoring himself on an error by RF Rosario
subset(d.single, RUNS_VALUE == max(RUNS_VALUE))[1,c("GAME_ID", "INN_CT", "BAT_ID", "STATE", "NEW_STATE", "RUNS_VALUE")]
# The least valuable single was Juan Uribe June 8, singling towards third, runner Freeman is called out for being hit by the batted ball
subset(d.single, RUNS_VALUE == min(RUNS_VALUE))[1,c("GAME_ID", "INN_CT", "BAT_ID", "STATE", "NEW_STATE", "RUNS_VALUE")]

# Value of a stolen base
steals <- subset(pbpdata2015, EVENT_CD == 6 | EVENT_CD == 4)
table(steals$STATE)
truehist(steals$RUNS_VALUE)
abline(v=mean(steals$RUNS_VALUE), lwd=3)
text(0.25, 2, "Mean Runs Value", pos=4)

steals.1001 <- subset(steals, STATE == "100 1")
table(steals.1001$EVENT_CD)
with(steals.1001, table(NEW_STATE))

# Chapter 5 Questions
# Work done using the 2015 dataset instead of 2011
# Solutions by Mike Nowicki

# 1. a)
double <- subset(pbpdata2015, EVENT_CD == 21)
triple <- subset(pbpdata2015, EVENT_CD == 22)
mean(double$RUNS_VALUE) # 0.743
mean(triple$RUNS_VALUE) # 1.031
mean(d.single$RUNS_VALUE) # 0.442
mean(d.homerun$RUNS_VALUE) # 1.386

# b) Compared to the weights from 2001 we see that the run values for singles, doubles, and homeruns
#    decreased in 2015, while the run value for triples increased by 0.01.

# 2.
hbp <- subset(pbpdata2015, EVENT_CD == 16)
hbp.100 <- subset(hbp, STATE == "100 0" | STATE == "100 1" | STATE == "100 2")
bb <- subset(pbpdata2015, EVENT_CD == 14 | EVENT_CD == 15)
bb.100 <- subset(bb, STATE == "100 0" | STATE == "100 1" | STATE == "100 2")
single.100 <- subset(d.single, STATE == "100 0" | STATE == "100 1" | STATE == "100 2")

mean(single.100$RUNS_VALUE) # Worth 0.4395 runs for getting a single with a runner on first
mean(bb.100$RUNS_VALUE) # Worth 0.3752 runs for getting a walk with a runner on first
mean(hbp.100$RUNS_VALUE) # Worth 0.3972 runs for getting HBP with a runner on first - odd that it's worth slightly more than a walk

# 3. I'm going to compare Trout to Harper instead using the 2015 dataset. Harper batted .330/.460/.649 with a 0.461 wOBA and 9.5 WAR,
#    while Trout slashed .299/.402/.590 with a 0.415 wOBA and 9 WAR season. Harper won the 2015 NL MVP while Trout fell short to
#    Donaldson for the AL MVP, he still put together an impressive season.
get.plyr.id <- function(lastname, firstname) {
  player <- subset(roster2015, roster2015$Last_Name == lastname & roster2015$First_Name == firstname)
  as.character(player$playerID)
}

plot.runs.value <- function(player) {
  with(player, stripchart(RUNS_VALUE ~ RUNNERS, vertical=TRUE, jitter=0.2, xlab="RUNNERS", method="jitter", pch=1, cex = 0.8))
  abline(h=0)
  
}

trout.id <- get.plyr.id("Trout", "Mike")
harper.id <- get.plyr.id("Harper", "Bryce")

harper <- subset(pbpdata2015, BAT_ID == harper.id)
trout <- subset(pbpdata2015, BAT_ID == trout.id)

trout$RUNNERS <- substr(trout$STATE, 1, 3)
trout.runs <- aggregate(trout$RUNS_VALUE, list(trout$RUNNERS), sum)
trout.PA <- aggregate(trout$RUNS_VALUE, list(trout$RUNNERS), length)
names(trout.runs)[2] <- "RUNS"
names(trout.PA)[2] <- "PA"
T <- merge(trout.PA, trout.runs)
sum(T$RUNS) # Totals 56.158 for Trout

harper$RUNNERS <- substr(harper$STATE, 1, 3)
harper.runs <- aggregate(harper$RUNS_VALUE, list(harper$RUNNERS), sum)
harper.PA <- aggregate(harper$RUNS_VALUE, list(harper$RUNNERS), length)
names(harper.runs)[2] <- "RUNS"
names(trout.PA)[2] <- "PA"
H <- merge(harper.PA, harper.runs)
sum(H$RUNS) # Totals 71.519 for Harper, impressive season.

plot.runs.value(trout)
plot.runs.value(harper)

# Harper:
# Group.1   x      RUNS
# 1     000 344 29.325314
# 2     001  19 -1.222546
# 3     010  56  7.953034
# 4     011   2  3.304750
# 5     100 157 23.158369
# 6     101  16  5.616402
# 7     110  60 -1.431395
# 8     111   8  4.814765
# Trout:
# Group.1  PA       RUNS
# 1     000 416 23.5113394
# 2     001  14  0.6844607
# 3     010  46  4.0952985
# 4     011  10  0.8514042
# 5     100 151  5.3494076
# 6     101  18  4.5642758
# 7     110  36  8.7040350
# 8     111   9  8.3976051

# Looking at the run data based on each of Harper/Trout PA and state we can see that Harper was much more productive than Trout hitting
# with a runner on first. Overall, however, Trout appears to be more consistent, not contributing any net negative runs over the course of
# the season, while Harper seems to have cost is team runs with runners on 3rd, or runners on first and second. Looking back at more traditional
# stats it would be hard to notice these types of details as both hit (around) .300 or better, and both had OBP's over .400, one would expect
# that both players would be positively contributing runs in their AB's over the season. Instead we see that it appears that Harper could
# further refine his approach in certain situations to ensure he does not cost the Nationals runs.

# 4. 